---
- name: Restart failed units.
  hosts: all
  gather_facts: true
  tasks:
    - name: Get failed systemd units.
      ansible.builtin.command: systemctl --failed --output json
      when: ansible_system == "Linux"
      register: systemd_failed_units
      changed_when: true

    - name: Restart failed unit(s).
      ansible.builtin.service:
        name: "{{ item.unit }}"
        state: restarted
      become: true
      loop: "{{ systemd_failed_units.stdout }}"
      when: ansible_system == "Linux"
