---
- name: Restart failed units.
  hosts: all
  gather_facts: true
  tasks:
    - name: Get systemd units.
      community.general.systemd_info:
      when: ansible_system == "Linux"
      register: systemd_units
      changed_when: false

    - name: Restart failed unit(s).
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: restarted
      when: ansible_system == "Linux"
      become: true
      loop: "{{ systemd_units.units | dict2items | community.general.json_query('[?value.activestate==`failed`].key') }}"
